name: Docker Image to Github Release
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      image-name:
        description: "Docker image name (e.g. ubuntu:latest)"
        required: true
        type: string
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "release"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions: write-all

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Sanitize image name
        id: sanitize
        run: |
          sanitized=$(echo "${{ inputs.image-name }}" | sed 's/[:\/]/_/g')
          echo "file_name=$sanitized" >> $GITHUB_OUTPUT

      # Runs a single command using the runners shell
      - name: Pull docker image
        run: docker pull "${{ inputs.image-name }}"

      # Runs a set of commands using the runners shell
      - name: Save image as file
        run: |
          docker save "${{ inputs.image-name }}" -o "${{ steps.sanitize.outputs.file_name }}.tar"
          gzip "${{ steps.sanitize.outputs.file_name }}.tar"
      - name: Create release on Github
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "release"
          prerelease: false
          title: "${{ steps.sanitize.outputs.file_name }}"
          files: "${{ steps.sanitize.outputs.file_name }}.tar.gz"
